insert into files (name, path) values('1+1', 'db/files/1+1.jpg');
insert into files (name, path) values('Двадцать одно', 'db/files/21.jpg');
insert into files (name, path) values('Клик с пультом по жизни', 'db/files/click.jpg');
insert into files (name, path) values('Джентельмены удачи', 'db/files/djentelmeny_udachi.jpg');
insert into files (name, path) values('Дом который построил Джек', 'db/files/dom_kotory_postroil_jack.jpg');
insert into files (name, path) values('Еще по одной', 'db/files/esche_po_odnoy.jpg');
insert into files (name, path) values('Евротур', 'db/files/eurotour.jpg');
insert into files (name, path) values('Форест Гамп', 'db/files/forest_gamp.jpg');
insert into files (name, path) values('Кингсман', 'db/files/kingsman.jpg');
insert into files (name, path) values('Леон', 'db/files/leon.jpg');
insert into files (name, path) values('Мальчишник в Вегасе', 'db/files/malchishnik_v_veg.jpg');
insert into files (name, path) values('Маска', 'db/files/maska.jpg');
insert into files (name, path) values('Зеркала', 'db/files/mirrors.jpg');
insert into files (name, path) values('Мы Миллеры', 'db/files/my_millery.jpg');
insert into files (name, path) values('Кошмар на улице Вязов', 'db/files/nightmare_on_elm_street.jpg');
insert into files (name, path) values('Сайлент Хилл', 'db/files/silent_hill.jpg');
insert into files (name, path) values('Стрингер', 'db/files/stringer.jpg');
insert into files (name, path) values('Роковое число 23', 'db/files/the_number_23.jpg');
insert into files (name, path) values('Троя', 'db/files/troy.jpg');
insert into files (name, path) values('В погоне за счастьем', 'db/files/v_pogone_za_sch.jpg');
insert into files (name, path) values('Васаби', 'db/files/wasabi.jpg');